_target_: model.gpt.GPT
name: gpt
n_layers: 8
n_recur: 1
detach_recur: false
cal_halt_loss: false
n_heads: 8
d_model: 512
vocab_size: 50257
max_seq_len: 1024
dropout: 0.1
norm_type: 'rmsnorm'
norm_eps: 1e-5
qk_normtype: "identity"
activation_type: 'squared_relu'
g1_gate: true
use_layer_scale: true
pad_token_id: -100 
tie_word_embeddings: false
