epochs: 10
grad_accum_steps: 32
logger: "tensorboard" # or "wandb"
compile: true
dtype: "float16"
early_stopping_patience: -1
val_every_n_steps: 200

optimizer:
  lr: 0.0006               # Target Peak LR for AdamW (embeddings/biases)
  muon_lr_multiplier: 33.3 # (0.0006 * 33.3 ≈ 0.02) Target Peak LR for Muon
  weight_decay: 0.1

scheduler:
  name: "cosine"
  # warmup_steps: 2000
  warmup_steps: 100
